// <auto-generated />
using FAQapp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQapp.Migrations
{
    [DbContext(typeof(QuestionContext))]
    partial class QuestionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FAQapp.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "A general purpose object oriented language that uses a concise, java-like syntax",
                            Category = "General",
                            QuestionText = "What is C#?",
                            Topic = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "A CSS framework for creating resposive web apps for multiple screen sizes",
                            Category = "General",
                            QuestionText = "What is Bootstrap?",
                            Topic = "Bootstrap"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "A general purpose scripting language that executes in a web browser",
                            Category = "General",
                            QuestionText = "What is JavaScript?",
                            Topic = "JavaScript"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "In 2011",
                            Category = "History",
                            QuestionText = "When was Bootstrap first released?",
                            Topic = "Bootstrap"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "In 2002.",
                            Category = "History",
                            QuestionText = "When was C# frist released?",
                            Topic = "C#"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
